VERSION = "2.0.0"

[[CURRENCIES]]
code = "BOLIVAR1936"
issuer = "GDHWACVGTT2W467AYCGYI3PVBXSA6QBJTGMA3QCRGUUQS5ZKR5PUPYGZ"
name = "BOLÍVAR 1936"
desc = """Esta pieza fue tokenizada por un humano llamado Drago.
Un buscador de significado que convirtió el metal en memoria,
y lo intangible en símbolo.
No buscaba fama… buscaba verdad."""
image = "https://animaargenta.com/nfts/bolivar1936/front.png"
conditions = "NFT único. Emisión bloqueada. No reemitible."
is_asset_anchored = false
display_decimals = 0
status = "live"

[[CURRENCIES]]
code = "UNIVERSDRAGO"
issuer = "GDJOJHTYWFRRXD3CEFJ7TRBHHQ7EQYKWU7NOXNICTYJG47A3EALY2SXK"
name = "Univers Drago - Acta Fundacional"
desc = "Primer NFT simbólico de fundación de Univers Drago. Nodo soberano híbrido físico-digital anclado en IPFS y Stellar."
conditions = "Emitido el 2025-06-15 como NFT fundacional único. Emisión cerrada."
image = "https://animaargenta-site/nfts/universdrago/universdrago.png"
anchor_asset_type = "NFT"
documentation = "https://bafybeicbf4kighfgxorcqcua2ib6bdf6j4rtqrtdhyzkum7fzjo5rxqpl4.ipfs.w3s.link"
policy = "soberano"

[DOCUMENTATION]
ORG_NAME = "Anima Argenta"
ORG_URL = "https://animaargenta.com"
ORG_DESCRIPTION = "Preservando memoria, transformando símbolo"
