name: Deploy a GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Clonar el repo
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Crear build
      run: npm run build

    - name: Configurar GitHub Pages
      uses: actions/configure-pages@v5

    - name: Preparar artefacto de GitHub Pages
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./dist
        include-hidden-files: true

    - name: Publicar en GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
